Repository Team-07-Looney/looney-general, pull requests merged in 2023-12, with the labels that each got.

#76 Feature/habits timer
  README.md
  frontend/src/lib/components/HabitItem.svelte
  frontend/src/lib/components/HabitsList.svelte
  frontend/src/lib/components/Header.svelte
  frontend/src/lib/components/Timer.svelte
  frontend/src/routes/+page.svelte
  frontend/src/routes/habits/+page.svelte
  frontend/src/routes/habits/[id]/+page.svelte
  frontend/src/routes/habits/[id]/edit/+page.svelte
  frontend/src/routes/habits/create/+page.svelte
  frontend/src/routes/login/+page.svelte
  frontend/src/routes/main/+page.svelte
  frontend/src/routes/register/+page.svelte
Labels: low priority

#83 Bugfix/home auth required
  backend/api-gateway/code/routes/index.js
  frontend/src/routes/home/+page.server.js
Labels: bugfix

#78 Feature - Time input for habits
  frontend/src/lib/components/Switcher.svelte
  frontend/src/lib/components/TimePicker.svelte
  frontend/src/routes/habits/[id]/edit/+page.server.js
  frontend/src/routes/habits/[id]/edit/+page.svelte
  frontend/src/routes/habits/create/+page.server.js
  frontend/src/routes/habits/create/+page.svelte
Labels: enhancement, high priority, bugfix

#88 Feature - Change password
  backend/api-gateway/code/controllers/authController.js
  backend/api-gateway/code/routes/index.js
  backend/users/code/controllers/userController.js
  backend/users/code/database/adapter.js
  backend/users/code/routes/index.js
  frontend/src/lib/components/authInput.svelte
  frontend/src/routes/profile/+page.server.js
  frontend/src/routes/profile/+page.svelte
  frontend/src/routes/register/+page.server.js
Labels: enhancement

#89 Bugfix - Testing pipeline
  .github/workflows/backend.yml
Labels: documentation, enhancement, bugfix

#90 Feature - Categories in Habits microservice
  backend/api-gateway/code/routes/index.js
  backend/habits/code/controllers/categoriesController.js
  backend/habits/code/controllers/habitsController.js
  backend/habits/code/controllers/recordsController.js
  backend/habits/code/database/categoriesAdapter.js
  backend/habits/code/database/database.js
  backend/habits/code/database/habitsAdapter.js
  backend/habits/code/database/recordsAdapter.js
  backend/habits/code/routes/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/img/checkDone.png
  frontend/src/img/checkUndone.png
  frontend/src/img/menuButton.png
  frontend/src/img/routineIcon0.png
  frontend/src/img/routineIcon1.png
  frontend/src/img/routineIcon2.png
  frontend/src/lib/components/CategoryItem.svelte
  frontend/src/lib/components/CircularProgressBar.svelte
  frontend/src/lib/components/HabitItem.svelte
  frontend/src/lib/components/Header.svelte
  frontend/src/lib/components/Timer.svelte
  frontend/src/routes/+page.svelte
  frontend/src/routes/categories/+page.server.js
  frontend/src/routes/categories/+page.svelte
  frontend/src/routes/categories/[categoryId]/+page.server.js
  frontend/src/routes/categories/[categoryId]/edit/+page.server.js
  frontend/src/routes/categories/[categoryId]/edit/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/+page.server.js
  frontend/src/routes/categories/[categoryId]/habits/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/+page.server.js
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/edit/+page.server.js
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/edit/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/create/+page.server.js
  frontend/src/routes/categories/[categoryId]/habits/create/+page.svelte
  frontend/src/routes/categories/create/+page.server.js
  frontend/src/routes/categories/create/+page.svelte
  frontend/src/routes/home/+page.svelte
  frontend/src/routes/login/+page.svelte
  frontend/src/routes/register/+page.svelte
Labels: enhancement, high priority

#99 Feature - add thought
  frontend/src/routes/moods/my-mood/+page.server.js
  frontend/src/routes/moods/my-mood/+page.svelte
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.server.js
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.svelte
  frontend/src/routes/moods/my-mood/thought/+page.server.js
  frontend/src/routes/moods/my-mood/thought/+page.svelte
  frontend/src/routes/moods/thoughts/+page.svelte
Labels: enhancement, high priority
