Repository Team-07-Looney/looney-general, pull requests merged in 2024-01, with the labels that each got.

#162 Bugfix/improvements found in 2nd User Testing
  backend/moods/code/database/database.js
  backend/moods/code/database/thoughtsAdapter.js
  frontend/src/img/checkDone.png
  frontend/src/img/myMoodOctopus.png
  frontend/src/lib/components/BottomMenu.svelte
  frontend/src/lib/components/CategoryItem.svelte
  frontend/src/lib/components/CircularProgressBar.svelte
  frontend/src/lib/components/HabitItem.svelte
  frontend/src/lib/components/MoodItem.svelte
  frontend/src/lib/components/OctopusButton.svelte
  frontend/src/lib/components/ReasonItem.svelte
  frontend/src/lib/components/ThoughtItem.svelte
  frontend/src/lib/components/Timer.svelte
  frontend/src/routes/categories/+page.server.js
  frontend/src/routes/categories/+page.svelte
  frontend/src/routes/categories/[categoryId]/edit/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/+page.server.js
  frontend/src/routes/categories/[categoryId]/habits/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/edit/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/create/+page.svelte
  frontend/src/routes/categories/create/+page.svelte
  frontend/src/routes/home/+page.server.js
  frontend/src/routes/home/+page.svelte
  frontend/src/routes/moods/+page.svelte
  frontend/src/routes/moods/my-mood/+page.svelte
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.server.js
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.svelte
  frontend/src/routes/moods/thoughts/+page.server.js
  frontend/src/routes/moods/thoughts/+page.svelte
  frontend/tailwind.config.js
Labels: bugfix

#168 Bugfix/attribute repeated
  frontend/src/routes/moods/my-mood/+page.svelte
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.svelte
Labels: bugfix

#105 Testing - user microservice
  backend/users/code/controllers/userController.js
  backend/users/code/tests/controllers/userController.test.js
Labels: documentation, enhancement

#176 Feature - Map
  backend/api-gateway/code/routes/index.js
  backend/moods/code/controllers/thoughtsController.js
  backend/moods/code/database/database.js
  backend/moods/code/database/thoughtsAdapter.js
  backend/moods/code/routes/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/img/location.png
  frontend/src/lib/components/mapComponents/Leaflet.svelte
  frontend/src/lib/components/mapComponents/Marker.svelte
  frontend/src/lib/components/mapComponents/Popup.svelte
  frontend/src/routes/map/+page.server.js
  frontend/src/routes/map/+page.svelte
  frontend/src/routes/moods/+page.svelte
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.server.js
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.svelte
Labels: enhancement, high priority

#183 Feature/predefined habits
  backend/api-gateway/code/routes/index.js
  backend/habits/code/controllers/categoriesController.js
  backend/habits/code/controllers/habitsController.js
  backend/habits/code/controllers/predefinedCategoriesController.js
  backend/habits/code/controllers/predefinedHabitsController.js
  backend/habits/code/controllers/recordsController.js
  backend/habits/code/database/categoriesAdapter.js
  backend/habits/code/database/database.js
  backend/habits/code/database/habitsAdapter.js
  backend/habits/code/database/predefinedCategoriesAdapter.js
  backend/habits/code/database/predefinedHabitsAdapter.js
  backend/habits/code/database/recordsAdapter.js
  backend/habits/code/routes/index.js
  frontend/src/lib/components/AuthInput.svelte
  frontend/src/routes/+layout.svelte
  frontend/src/routes/categories/[categoryId]/edit/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/edit/+page.server.js
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/edit/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/create/+page.server.js
  frontend/src/routes/categories/[categoryId]/habits/create/+page.svelte
  frontend/src/routes/categories/create/+page.svelte
  frontend/src/routes/login/+page.svelte
  frontend/src/routes/moods/my-mood/createMood/+page.svelte
  frontend/src/routes/moods/my-mood/createReason/+page.svelte
  frontend/src/routes/profile/+page.svelte
  frontend/src/routes/register/+page.svelte
Labels: enhancement, medium priority

#188 Fix - map
  frontend/src/lib/components/mapComponents/Leaflet.svelte
  frontend/src/routes/map/+page.server.js
  frontend/src/routes/map/+page.svelte
Labels: high priority, bugfix

#174 Feature/advice and stats
  backend/api-gateway/code/controllers/authController.js
  backend/api-gateway/code/routes/index.js
  backend/habits/code/controllers/habitRecordsController.js
  backend/habits/code/controllers/recordsController.js
  backend/habits/code/database/database.js
  backend/habits/code/database/habitRecordsAdapter.js
  backend/habits/code/routes/index.js
  backend/moods/code/controllers/adviceController.js
  backend/moods/code/controllers/adviceGroupsController.js
  backend/moods/code/controllers/adviceRecordsController.js
  backend/moods/code/controllers/moodRecordsController.js
  backend/moods/code/controllers/thoughtsController.js
  backend/moods/code/database/adviceAdapter.js
  backend/moods/code/database/adviceGroupsAdapter.js
  backend/moods/code/database/adviceRecordsAdapter.js
  backend/moods/code/database/database.js
  backend/moods/code/database/moodRecordsAdapter.js
  backend/moods/code/database/moodTypesAdapter.js
  backend/moods/code/database/moodsAdapter.js
  backend/moods/code/database/reasonsAdapter.js
  backend/moods/code/database/thoughtsAdapter.js
  backend/moods/code/routes/index.js
  frontend/package-lock.json
  frontend/src/img/adviceIcons/Art and Craft.png
  frontend/src/img/adviceIcons/Bake Muffins.png
  frontend/src/img/adviceIcons/Call Family.png
  frontend/src/img/adviceIcons/Do Yoga.png
  frontend/src/img/adviceIcons/Explore a Park.png
  frontend/src/img/adviceIcons/Go to a Café.png
  frontend/src/img/adviceIcons/Listen to Music.png
  frontend/src/img/adviceIcons/Meditate.png
  frontend/src/img/adviceIcons/Movie Night.png
  frontend/src/img/adviceIcons/Outdoor Walk.png
  frontend/src/img/adviceIcons/Read a Book.png
  frontend/src/img/adviceIcons/Talk to a Friend.png
  frontend/src/img/adviceIcons/Try a new Recipe.png
  frontend/src/img/adviceIcons/Try new Outfits.png
  frontend/src/img/adviceIcons/Warm Bath.png
  frontend/src/lib/components/AdviceItem.svelte
  frontend/src/lib/components/AdviceTrackerItem.svelte
  frontend/src/lib/components/ProgressBar.svelte
  frontend/src/routes/categories/[categoryId]/habits/+page.server.js
  frontend/src/routes/moods/+page.server.js
  frontend/src/routes/moods/+page.svelte
  frontend/src/routes/moods/my-mood/+page.server.js
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.server.js
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.svelte
  frontend/src/routes/moods/my-mood/[recordId]/thought/advice/+page.server.js
  frontend/src/routes/moods/my-mood/[recordId]/thought/advice/+page.svelte
  frontend/src/routes/moods/thoughts/+page.server.js
  frontend/src/routes/moods/thoughts/[thoughtsId]/+page.server.js
  frontend/src/routes/moods/tracker/+page.server.js
  frontend/src/routes/moods/tracker/+page.svelte
  frontend/tailwind.config.js
  package-lock.json
Labels: enhancement, high priority

#190 Feature - delete confirmation
  frontend/src/lib/bluetoothMessage.js
  frontend/src/lib/components/CategoryItem.svelte
  frontend/src/lib/components/DeleteConfirmationPopup.svelte
  frontend/src/lib/components/HabitItem.svelte
  frontend/src/lib/components/ThoughtItem.svelte
  frontend/src/lib/popup.js
  frontend/src/routes/+layout.svelte
  frontend/src/routes/categories/[categoryId]/edit/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/edit/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/create/+page.svelte
  frontend/src/routes/categories/create/+page.svelte
Labels: enhancement, high priority

#193 Fix - habit records
  frontend/src/routes/categories/[categoryId]/habits/+page.server.js
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/+page.server.js
Labels: high priority, bugfix

#180 Feature/categories icons
  backend/habits/code/database/categoriesAdapter.js
  backend/habits/code/database/database.js
  backend/habits/code/database/predefinedCategoriesAdapter.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/img/routineIcon0.png
  frontend/src/img/routineIcon1.png
  frontend/src/img/routineIcon2.png
  frontend/src/lib/components/AuthInput.svelte
  frontend/src/lib/components/CategoryItem.svelte
  frontend/src/lib/components/HabitItem.svelte
  frontend/src/lib/components/IconsMenu.svelte
  frontend/src/lib/components/ProgressBar.svelte
  frontend/src/routes/+layout.svelte
  frontend/src/routes/categories/+page.svelte
  frontend/src/routes/categories/[categoryId]/edit/+page.server.js
  frontend/src/routes/categories/[categoryId]/edit/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/+page.server.js
  frontend/src/routes/categories/create/+page.server.js
  frontend/src/routes/categories/create/+page.svelte
  frontend/src/routes/moods/my-mood/[recordId]/thought/+page.svelte
  frontend/src/routes/moods/my-mood/[recordId]/thought/advice/+page.svelte
  frontend/src/routes/moods/tracker/+page.svelte
Labels: enhancement, low priority

#195 Feature - Connect Looney
  arduino-sketch/bleAndMatrix.ino
  backend/api-gateway/code/routes/index.js
  backend/arduino/.gitignore
  backend/arduino/code/package-lock.json
  backend/arduino/code/package.json
  backend/arduino/code/routes/index.js
  backend/arduino/code/start.js
  backend/arduino/code/variables.env.example
  backend/users/code/package-lock.json
  docker-compose.yml
  frontend/src/lib/bluetoothConnection.js
  frontend/src/lib/bluetoothStore.js
  frontend/src/lib/components/BuyLooney.svelte
Labels: enhancement, high priority

#197 Hotfix - Fix the character length to 8
  frontend/src/routes/profile/+page.server.js
Labels: high priority, bugfix

#198 Hotfix - Fix the character length to 8
  frontend/src/routes/profile/+page.server.js
Labels: high priority, bugfix

#200 Fix deletion of categories and habits
  frontend/src/lib/components/CategoryItem.svelte
  frontend/src/lib/components/HabitItem.svelte
  frontend/src/lib/popup.js
  frontend/src/routes/categories/+page.svelte
  frontend/src/routes/categories/[categoryId]/+page.server.js
  frontend/src/routes/categories/[categoryId]/habits/+page.svelte
  frontend/src/routes/categories/[categoryId]/habits/[habitId]/+page.server.js
Labels: bug, bugfix

#205 CIN - Workflow for publishing to dockerhub
  .github/workflows/publish.yml
  backend/api-gateway/Dockerfile
  backend/arduino/Dockerfile
  backend/common/Dockerfile
  backend/habits/Dockerfile
  backend/moods/Dockerfile
  backend/users/Dockerfile
Labels: documentation, enhancement

#209 Updating Pipelines
  .github/workflows/publish.yml
  .github/workflows/unit-tests-report.yml
  .github/workflows/unit-tests.yml
  backend/api-gateway/Dockerfile
  backend/arduino/Dockerfile
  backend/common/Dockerfile
  backend/habits/Dockerfile
  backend/moods/Dockerfile
  backend/moods/code/database/database.js
  backend/moods/code/package-lock.json
  backend/moods/code/package.json
  backend/moods/code/tests/controllers/adviceRecordsController.test.js
  backend/moods/code/tests/controllers/moodRecordsController.test.js
  backend/moods/code/tests/database/adviceRecordsAdapter.test.js
  backend/moods/code/tests/database/database.test.js
  backend/moods/code/tests/database/moodRecordsAdapter.test.js
  backend/moods/code/tests/test-setup.js
  backend/users/Dockerfile
  backend/users/code/package-lock.json
  backend/users/code/package.json
  backend/users/code/tests/controllers/userController.test.js
Labels: documentation, enhancement
